# Credits By efe

name: WINCRD

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Type CRD Code'
        required: true
      pincode:
        description: 'Set Pin'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: CRD Setupping
      run: ./main.ps1
    - name: CRD Starting
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive
      run: ./timeout.ps1
