name: WINCRD

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Nhập code CRD (lấy trong Chrome Remote Desktop [Powershell] ) '
        required: true
      pincode:
        description: 'Nhập mã pin [tối thiểu 6 số]'
        required: true
  
jobs:
  build:
    runs-on: windows-lastest

    steps:
    - uses: actions/checkout@v2
    - name: CRD Setupping
      run: ./main.ps1
    - name: CRD Starting
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive
      run: ./timeout.ps1
